apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: pinot-cluster
networking:
  #ipFamily: dual
  ipFamily: ipv4
  #apiServerAddress: 127.0.0.1
nodes:
  - role: control-plane
    image: ${KIND_IMAGE}
    extraMounts: []
  - role: worker
    image: ${KIND_IMAGE}
    extraMounts: []
  - role: worker
    image: ${KIND_IMAGE}
    extraMounts: []
  - role: worker
    image: ${KIND_IMAGE}
    extraMounts: []
